title: Mount Balrior
description: Guides and information for all bosses in the Mount Balrior raid instance. 
theme: just-the-docs

url: https://silverhalf.github.io/mount-balrior

aux_links:
  "Source Code": 
    - "https://github.com/SilverHalf/temple-of-febe"

aux_links_new_tab: true
